version: "3.8"

services:
  GraceCraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TYPE: "Vanilla"
      MOTD: "Vanilla Minecraft, Chill Vibes Only"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      restart: always
    volumes:
    - /home/docker/gracecraft:/data

  PeterCraft:
    image: itzg/minecraft-server
    ports:
      - 25566:25565
    environment:
      TYPE: "Forge"
      MOTD: "Vanilla Minecraft, Chill Vibes Only"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      restart: unless-stopped 
    volumes:
    - /home/docker/petercraft:/data